// Indian States and their Cities
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
].sort()

export const STATE_CITIES: Record<string, string[]> = {
  'Andhra Pradesh': [
    'Visakhapatnam',
    'Vijayawada',
    'Guntur',
    'Nellore',
    'Kurnool',
    'Rajahmundry',
    'Tirupati',
    'Kakinada',
    'Kadapa',
    'Anantapur',
    'Eluru',
    'Ongole',
    'Nandyal',
    'Machilipatnam',
    'Adoni',
    'Tenali',
    'Chittoor',
    'Hindupur',
    'Proddatur',
    'Bhimavaram',
  ],
  'Arunachal Pradesh': [
    'Itanagar',
    'Naharlagun',
    'Tawang',
    'Bomdila',
    'Pasighat',
    'Tezu',
    'Ziro',
    'Daporijo',
    'Along',
    'Khonsa',
  ],
  'Assam': [
    'Guwahati',
    'Silchar',
    'Dibrugarh',
    'Jorhat',
    'Nagaon',
    'Tinsukia',
    'Tezpur',
    'Bongaigaon',
    'Dhubri',
    'Diphu',
    'North Lakhimpur',
    'Karimganj',
    'Goalpara',
    'Sivasagar',
    'Barpeta',
    'Golaghat',
    'Hailakandi',
    'Mangaldoi',
    'Morigaon',
  ],
  'Bihar': [
    'Patna',
    'Gaya',
    'Bhagalpur',
    'Muzaffarpur',
    'Purnia',
    'Darbhanga',
    'Bihar Sharif',
    'Arrah',
    'Begusarai',
    'Katihar',
    'Munger',
    'Chhapra',
    'Saharsa',
    'Sasaram',
    'Hajipur',
    'Dehri',
    'Bettiah',
    'Siwan',
    'Motihari',
    'Nawada',
  ],
  'Chhattisgarh': [
    'Raipur',
    'Bhilai',
    'Bilaspur',
    'Durg',
    'Korba',
    'Rajnandgaon',
    'Raigarh',
    'Jagdalpur',
    'Ambikapur',
    'Dhamtari',
    'Chirmiri',
    'Mahasamund',
    'Dalli-Rajhara',
    'Kanker',
    'Kawardha',
  ],
  'Goa': [
    'Panaji',
    'Margao',
    'Vasco da Gama',
    'Mapusa',
    'Ponda',
    'Bicholim',
    'Curchorem',
    'Valpoi',
    'Sanguem',
    'Canacona',
  ],
  'Gujarat': [
    'Ahmedabad',
    'Surat',
    'Vadodara',
    'Rajkot',
    'Bhavnagar',
    'Jamnagar',
    'Gandhinagar',
    'Junagadh',
    'Gandhidham',
    'Anand',
    'Navsari',
    'Morbi',
    'Nadiad',
    'Surendranagar',
    'Bharuch',
    'Mehsana',
    'Bhuj',
    'Porbandar',
    'Palanpur',
    'Valsad',
  ],
  'Haryana': [
    'Faridabad',
    'Gurgaon',
    'Panipat',
    'Ambala',
    'Yamunanagar',
    'Rohtak',
    'Hisar',
    'Karnal',
    'Sonipat',
    'Panchkula',
    'Bhiwani',
    'Sirsa',
    'Bahadurgarh',
    'Jind',
    'Thanesar',
    'Kaithal',
    'Rewari',
    'Palwal',
    'Hansi',
    'Narnaul',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Mandi',
    'Solan',
    'Dharamshala',
    'Bilaspur',
    'Kullu',
    'Chamba',
    'Hamirpur',
    'Una',
    'Nahan',
    'Palampur',
    'Kangra',
    'Kasauli',
    'Manali',
  ],
  'Jharkhand': [
    'Jamshedpur',
    'Dhanbad',
    'Ranchi',
    'Bokaro Steel City',
    'Hazaribagh',
    'Deoghar',
    'Giridih',
    'Phusro',
    'Adityapur',
    'Ramgarh',
    'Chas',
    'Medininagar',
    'Chaibasa',
    'Jhumri Tilaiya',
    'Sahibganj',
  ],
  'Karnataka': [
    'Bangalore',
    'Mysore',
    'Hubli',
    'Mangalore',
    'Belgaum',
    'Gulbarga',
    'Davangere',
    'Bellary',
    'Bijapur',
    'Shimoga',
    'Tumkur',
    'Raichur',
    'Bidar',
    'Hospet',
    'Hassan',
    'Udupi',
    'Chitradurga',
    'Kolar',
    'Mandya',
    'Chikmagalur',
  ],
  'Kerala': [
    'Kochi',
    'Kozhikode',
    'Thrissur',
    'Malappuram',
    'Thiruvananthapuram',
    'Kannur',
    'Kollam',
    'Alappuzha',
    'Kottayam',
    'Palakkad',
    'Manjeri',
    'Thalassery',
    'Ponnani',
    'Vatakara',
    'Kanhangad',
  ],
  'Madhya Pradesh': [
    'Indore',
    'Bhopal',
    'Gwalior',
    'Jabalpur',
    'Raipur',
    'Ujjain',
    'Sagar',
    'Dewas',
    'Satna',
    'Ratlam',
    'Rewa',
    'Murwara',
    'Singrauli',
    'Burhanpur',
    'Khandwa',
    'Morena',
    'Bhind',
    'Chhindwara',
    'Guna',
    'Shivpuri',
  ],
  'Maharashtra': [
    'Mumbai',
    'Pune',
    'Nagpur',
    'Thane',
    'Nashik',
    'Aurangabad',
    'Solapur',
    'Amravati',
    'Nanded',
    'Kolhapur',
    'Sangli',
    'Jalgaon',
    'Akola',
    'Latur',
    'Ahmednagar',
    'Chandrapur',
    'Parbhani',
    'Ichalkaranji',
    'Jalna',
    'Bhusawal',
  ],
  'Manipur': [
    'Imphal',
    'Thoubal',
    'Kakching',
    'Ukhrul',
    'Churachandpur',
    'Bishnupur',
    'Tamenglong',
    'Senapati',
    'Jiribam',
  ],
  'Meghalaya': [
    'Shillong',
    'Tura',
    'Jowai',
    'Nongstoin',
    'Williamnagar',
    'Baghmara',
    'Resubelpara',
    'Mairang',
  ],
  'Mizoram': [
    'Aizawl',
    'Lunglei',
    'Saiha',
    'Champhai',
    'Kolasib',
    'Serchhip',
    'Lawngtlai',
    'Mamit',
  ],
  'Nagaland': [
    'Dimapur',
    'Kohima',
    'Mokokchung',
    'Tuensang',
    'Wokha',
    'Zunheboto',
    'Mon',
    'Phek',
  ],
  'Odisha': [
    'Bhubaneswar',
    'Cuttack',
    'Rourkela',
    'Berhampur',
    'Sambalpur',
    'Puri',
    'Baleshwar',
    'Bhadrak',
    'Baripada',
    'Balangir',
    'Jharsuguda',
    'Bargarh',
    'Paradip',
    'Bhawanipatna',
    'Dhenkanal',
    'Barbil',
    'Kendujhar',
    'Sunabeda',
    'Rayagada',
    'Jeypore',
  ],
  'Punjab': [
    'Ludhiana',
    'Amritsar',
    'Jalandhar',
    'Patiala',
    'Bathinda',
    'Pathankot',
    'Hoshiarpur',
    'Batala',
    'Moga',
    'Abohar',
    'Khanna',
    'Phagwara',
    'Kapurthala',
    'Muktsar',
    'Barnala',
    'Firozpur',
    'Chandigarh',
    'Mohali',
    'Rupnagar',
    'Faridkot',
  ],
  'Rajasthan': [
    'Jaipur',
    'Jodhpur',
    'Kota',
    'Bikaner',
    'Ajmer',
    'Udaipur',
    'Bhilwara',
    'Alwar',
    'Bharatpur',
    'Sikar',
    'Pali',
    'Tonk',
    'Hanumangarh',
    'Beawar',
    'Dausa',
    'Churu',
    'Ganganagar',
    'Baran',
    'Chittorgarh',
    'Jhunjhunu',
  ],
  'Sikkim': [
    'Gangtok',
    'Namchi',
    'Mangan',
    'Gyalshing',
    'Singtam',
    'Rangpo',
    'Jorethang',
  ],
  'Tamil Nadu': [
    'Chennai',
    'Coimbatore',
    'Madurai',
    'Tiruchirappalli',
    'Salem',
    'Tirunelveli',
    'Erode',
    'Vellore',
    'Dindigul',
    'Thanjavur',
    'Tuticorin',
    'Nagercoil',
    'Hosur',
    'Kanchipuram',
    'Karaikudi',
    'Neyveli',
    'Cuddalore',
    'Kumbakonam',
    'Tiruvannamalai',
    'Pollachi',
  ],
  'Telangana': [
    'Hyderabad',
    'Warangal',
    'Nizamabad',
    'Karimnagar',
    'Ramagundam',
    'Khammam',
    'Mahbubnagar',
    'Mancherial',
    'Adilabad',
    'Suryapet',
    'Jagtial',
    'Miryalaguda',
    'Nalgonda',
    'Siddipet',
    'Bhongir',
    'Bodhan',
    'Palwancha',
    'Kothagudem',
    'Mahabubabad',
    'Sangareddy',
  ],
  'Tripura': [
    'Agartala',
    'Udaipur',
    'Dharmanagar',
    'Kailasahar',
    'Belonia',
    'Khowai',
    'Ambassa',
  ],
  'Uttar Pradesh': [
    'Lucknow',
    'Kanpur',
    'Agra',
    'Meerut',
    'Varanasi',
    'Allahabad',
    'Bareilly',
    'Aligarh',
    'Moradabad',
    'Saharanpur',
    'Gorakhpur',
    'Noida',
    'Firozabad',
    'Jhansi',
    'Muzaffarnagar',
    'Mathura',
    'Rampur',
    'Shahjahanpur',
    'Farrukhabad',
    'Fatehpur',
  ],
  'Uttarakhand': [
    'Dehradun',
    'Haridwar',
    'Roorkee',
    'Haldwani',
    'Rudrapur',
    'Kashipur',
    'Rishikesh',
    'Pithoragarh',
    'Ramnagar',
    'Manglaur',
    'Nainital',
    'Mussoorie',
    'Almora',
    'Kotdwara',
  ],
  'West Bengal': [
    'Kolkata',
    'Howrah',
    'Durgapur',
    'Asansol',
    'Siliguri',
    'Bardhaman',
    'Malda',
    'Baharampur',
    'Habra',
    'Kharagpur',
    'Shantipur',
    'Krishnanagar',
    'Barasat',
    'Balurghat',
    'Jalpaiguri',
    'Raiganj',
    'Medinipur',
    'Chandannagar',
    'Kalyani',
    'Bidhannagar',
  ],
  'Andaman and Nicobar Islands': [
    'Port Blair',
    'Diglipur',
    'Mayabunder',
    'Rangat',
    'Car Nicobar',
  ],
  'Chandigarh': [
    'Chandigarh',
  ],
  'Dadra and Nagar Haveli and Daman and Diu': [
    'Daman',
    'Diu',
    'Silvassa',
  ],
  'Delhi': [
    'New Delhi',
    'Delhi',
    'North Delhi',
    'South Delhi',
    'East Delhi',
    'West Delhi',
    'Central Delhi',
    'Noida',
    'Gurgaon',
    'Faridabad',
    'Ghaziabad',
  ],
  'Jammu and Kashmir': [
    'Srinagar',
    'Jammu',
    'Anantnag',
    'Baramulla',
    'Sopore',
    'Kathua',
    'Udhampur',
    'Poonch',
    'Rajouri',
    'Kupwara',
  ],
  'Ladakh': [
    'Leh',
    'Kargil',
  ],
  'Lakshadweep': [
    'Kavaratti',
    'Agatti',
    'Amini',
  ],
  'Puducherry': [
    'Puducherry',
    'Karaikal',
    'Mahe',
    'Yanam',
  ],
}

// Helper function to get cities for a state
export function getCitiesForState(state: string): string[] {
  return STATE_CITIES[state] || []
}



